# -*- coding: utf-8 -*-
"""Annaflight.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AG6CifrH5K6hr-INsiNdKLSu3tYsoVTI
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("threnjen/2019-airline-delays-and-cancellations")

print("Path to dataset files:", path)

import os

os.listdir(path)

#Tamaño real del csv

import pandas as pd

# Definir la ruta al CSV
csv_path = "full_data_flightdelay.csv"  # o la ruta completa si está en otra carpeta

# Cargar solo las columnas necesarias
df = pd.read_csv(
    csv_path,
    usecols=["UniqueCarrier", "DepDelay"]
)

# Crear columna 'delayed' para vuelos con retraso >= 15 minutos
df["delayed"] = (df["DepDelay"] >= 15).astype(int)

# Mostrar primeras filas para confirmar
df.head()

#Cargo muestra dataframe de 100k

import pandas as pd

df = pd.read_csv(
    f"{path}/full_data_flightdelay.csv",
    nrows=100_000
)

df.shape

#Columnas

df.columns

df["delayed"] = df["DEP_DEL15"]
df["hour"] = df["DEP_TIME_BLK"].str.slice(0, 2).astype(int)
print("Delay rate:", df["delayed"].mean())

#Prueba binaria

df["delayed"].unique()

#Retraso por hora del día, agrupo hour y delayed y gráfica. Quiero saber si hay diferencias de probabilidad y si tienen realismo.

hour_delay = (
df.groupby("hour")["delayed"]   #la media del binario por grupo se interpreta como probabilidad.
.mean()
.sort_index()
)
print(hour_delay)



import matplotlib.pyplot as plt


plt.figure(figsize=(10,4))
hour_delay.plot(kind="line", marker="o")
plt.title("Probability of Flight Delay by Scheduled Departure Hour")
plt.xlabel("Hour of Day")
plt.ylabel("Delay Probability")
plt.grid(True)
plt.show()

#Retraso x distancia (rango de millas) y gráfica

delay_by_dist = (
    df.groupby("DISTANCE_GROUP")["delayed"]
      .mean()
)

delay_by_dist


delay_by_dist.plot(kind="bar", title="Delay rate by distance group")

#Creo día de la semana

delay_by_day = (
    df.groupby("DAY_OF_WEEK")["DEP_DEL15"]
      .mean()
)


import matplotlib.pyplot as plt

plt.figure()
delay_by_day.plot(kind="bar")
plt.xlabel("Day of Week (1=Mon, 7=Sun)")
plt.ylabel("Delay rate")
plt.title("Departure delay rate by day of week")
plt.show()

#top 10 aerolíneas

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("full_data_flightdelay.csv")
df.head()

df["delayed"].value_counts(normalize=True) #Variable objetiva binaria prueba

hour_delay = (
    df.groupby("hour")["delayed"]
    .mean()
)

hour_delay.std()

# Este criterio mide cuánto cambia la probabilidad de retraso a lo largo del día;
# si la variación es alta, significa que la hora del vuelo influye de forma real
# en los retrasos, y el ratio entre datasets nos permite comparar cuál captura
# mejor ese patrón temporal sin necesidad de entrenar ni optimizar modelos.

# Al medir la variación de la probabilidad de retraso según la hora, verificamos
# que la hora del vuelo tiene impacto real, y usando el ratio podemos decidir
# qué dataset conserva mejor esa señal predictiva sin incurrir en mayor coste
# computacional.