# -*- coding: utf-8 -*-
"""JaviFlight.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ldgzwa2PnJqDL6X1eQfWXoSxvDNhTE1t

Objetivo:
Predecir si un vuelo sufrirá retraso (≥15 min) usando únicamente información
disponible antes del despegue.

Tipo de problema:
Clasificación binaria (0 = no retraso, 1 = retraso).

Dataset:
Vuelos comerciales en EE.UU. (2019–2023)

"
"""

#Importo el dataset

import kagglehub

path = kagglehub.dataset_download(
    "patrickzel/flight-delay-and-cancellation-dataset-2019-2023"
)

print("Dataset path:", path)

#Exploro archivos

import os

os.listdir(path)

#Tamaño real del csv

import pandas as pd


csv_path = f"{path}/flights_sample_3m.csv"


num_columnas = pd.read_csv(csv_path, nrows=0).shape[1]
num_filas = sum(1 for _ in open(csv_path, encoding="utf-8")) - 1


print(f"Filas reales del CSV: {num_filas}")
print(f"Columnas reales del CSV: {num_columnas}")

#Cargo muestra dataframe de 100k

import pandas as pd

df = pd.read_csv(
    f"{path}/flights_sample_3m.csv",
    nrows=100_000
)

df.shape

#Columnas

df.columns

#Creo varible temporal hour y variable objetivo delayed, evitamos leakage (información no disponible cuando se hace la predicción).
#Hora programada y no real y 15 minutos.

df["hour"] = df["CRS_DEP_TIME"] // 100   #nos quedamos con las horas
df["delayed"] = (df["DEP_DELAY"] >= 15).astype(int)  #y la hacemos binaria

print("Delay rate:", df["delayed"].mean()) #binaria: la media representa la propabilidad de delay

#Prueba binaria

df["delayed"].unique()

#Retraso por hora del día, agrupo hour y delayed y gráfica. Quiero saber si hay diferencias de probabilidad y si tienen realismo.

hour_delay = (
df.groupby("hour")["delayed"]   #la media del binario por grupo se interpreta como probabilidad.
.mean()
.sort_index()
)
print(hour_delay)



import matplotlib.pyplot as plt


plt.figure(figsize=(10,4))
hour_delay.plot(kind="line", marker="o")
plt.title("Probability of Flight Delay by Scheduled Departure Hour")
plt.xlabel("Hour of Day")
plt.ylabel("Delay Probability")
plt.grid(True)
plt.show()

#Retraso x distancia (rango de millas) y gráfica

df["distance_bin"] = pd.qcut(df["DISTANCE"], q=5)


distance_delay = (
df.groupby("distance_bin", observed=True)["delayed"]
.mean()
)
print(distance_delay)


plt.figure(figsize=(8,4))
distance_delay.plot(kind="bar")
plt.title("Delay Probability by Flight Distance")
plt.ylabel("Delay Probability")
plt.xticks(rotation=45)
plt.grid(axis="y")
plt.show()

#Creo día de la semana

df["FL_DATE"] = pd.to_datetime(df["FL_DATE"])
df["day_of_week"] = df["FL_DATE"].dt.dayofweek

#Retraso por día de la semana

dow_delay = (
    df.groupby("day_of_week")["delayed"]
    .mean()
    .sort_index()
)

plt.figure(figsize=(8,4))
dow_delay.plot(kind="bar")
plt.title("Delay Probability by Day of Week (0=Monday)")
plt.xlabel("Day of Week")
plt.ylabel("Delay Probability")
plt.show()

#top 10 aerolíneas


airline_delay = (
df.groupby("AIRLINE")["delayed"]
.mean()
.sort_values(ascending=False)
.head(10)
)
print(airline_delay)


plt.figure(figsize=(8,4))
airline_delay.plot(kind="bar")
plt.title("Top 10 Airlines by Delay Probability")
plt.ylabel("Delay Probability")
plt.show()

df["delayed"].value_counts(normalize=True) #Variable objetiva binaria prueba

# 82.34% NO se retrasan, 17.66% SI se retrasan

# Comparar mañana vs noche
morning = df[df["hour"].between(6, 11)]["delayed"].mean()
night = df[df["hour"].between(18, 23)]["delayed"].mean()

print("Morning delay prob:", round(morning, 3))
print("Night delay prob:", round(night, 3))
print("Difference:", round(night - morning, 3))

hour_delay = (
    df.groupby("hour")["delayed"]
    .mean()
)

hour_delay.std()

# Este criterio mide cuánto cambia la probabilidad de retraso a lo largo del día;
# si la variación es alta, significa que la hora del vuelo influye de forma real
# en los retrasos, y el ratio entre datasets nos permite comparar cuál captura
# mejor ese patrón temporal sin necesidad de entrenar ni optimizar modelos.

# Al medir la variación de la probabilidad de retraso según la hora, verificamos
# que la hora del vuelo tiene impacto real, y usando el ratio podemos decidir
# qué dataset conserva mejor esa señal predictiva sin incurrir en mayor coste
# computacional.

#-Contiene un gran volumen de datos reales.

#-Incluye variables temporales y operativas conocidas antes del vuelo.

#-Permite definir una variable objetivo clara siguiendo estándares de aviación  (vuelo retrasado si la salida es ≥ 15 minutos).

#-Presenta suficiente detalle para análisis por hora, distancia,aerolínea y día de la semana.

#Durante el preprocesamiento se evitó explícitamente el uso de variables que introducen data leakage (información no disponible cuando se hace la predicción),
#garantizando que los análisis y los posibles modelos predictivos sean válidos, realistas y reproducibles.