# -*- coding: utf-8 -*-
"""Alex colab (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4ULTky6RJWidjbq4WzodILtIt20V50L
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("giovamata/airlinedelaycauses")

print("Path to dataset files:", path)

import pandas as pd

#Tamaño real del csv

csv_path = f"{path}/DelayedFlights.csv"


num_columnas = pd.read_csv(csv_path, nrows=0).shape[1]
num_filas = sum(1 for _ in open(csv_path, encoding="utf-8")) - 1


print(f"Filas reales del CSV: {num_filas}")
print(f"Columnas reales del CSV: {num_columnas}")

#Cargo muestra dataframe de 100k

import pandas as pd

df = pd.read_csv(
    f"{path}/DelayedFlights.csv",
    nrows=100_000
)

df.shape

#Columnas

df.columns

# Hora programada de salida (nos quedamos solo con la hora)
df["hour"] = df["CRSDepTime"] // 100

# Variable binaria de retraso (1 = retraso >= 15 min)
df["delayed"] = (df["DepDelay"] >= 15).astype(int)

#Prueba binaria

df["delayed"].unique()

#Retraso por hora del día, agrupo hour y delayed y gráfica. Quiero saber si hay diferencias de probabilidad y si tienen realismo.

hour_delay = (
df.groupby("hour")["delayed"]   #la media del binario por grupo se interpreta como probabilidad.
.mean()
.sort_index()
)
print(hour_delay)



import matplotlib.pyplot as plt


plt.figure(figsize=(10,4))
hour_delay.plot(kind="line", marker="o")
plt.title("Probability of Flight Delay by Scheduled Departure Hour")
plt.xlabel("Hour of Day")
plt.ylabel("Delay Probability")
plt.grid(True)
plt.show()

# Crear rangos de distancia (quintiles)
df["distance_bin"] = pd.qcut(df["Distance"], q=5)

# Probabilidad de retraso por rango de distancia
delay_by_distance = df.groupby("distance_bin")["delayed"].mean()



delay_by_distance.plot(kind="bar", title="Probabilidad de retraso por distancia")

#Creo día de la semana

df["day_of_week"] = df["DayOfWeek"]

#Retraso por día de la semana

dow_delay = (
    df.groupby("day_of_week")["delayed"]
    .mean()
    .sort_index()
)

plt.figure(figsize=(8,4))
dow_delay.plot(kind="bar")
plt.title("Delay Probability by Day of Week (0=Monday)")
plt.xlabel("Day of Week")
plt.ylabel("Delay Probability")
plt.show()

#top 10 aerolíneas

import pandas as pd
import matplotlib.pyplot as plt

# Ruta correcta al CSV
csv_path = f"{path}/DelayedFlights.csv"

# Cargar solo lo necesario (eficiente)
df = pd.read_csv(
    csv_path,
    usecols=["UniqueCarrier", "DepDelay"]
)

# Crear variable binaria de retraso (>=15 min)
df["delayed"] = (df["DepDelay"] >= 15).astype(int)

# Top 10 aerolíneas con mayor probabilidad de retraso
top10_airlines = (
    df.groupby("UniqueCarrier")["delayed"]
      .mean()
      .sort_values(ascending=False)
      .head(10)
)

# Mostrar tabla
print(top10_airlines)

# Gráfica
plt.figure(figsize=(10,6))
top10_airlines.plot(kind="bar")
plt.title("Top 10 aerolíneas con mayor probabilidad de retraso")
plt.xlabel("Aerolínea (UniqueCarrier)")
plt.ylabel("Probabilidad de retraso (≥ 15 min)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df["delayed"].value_counts(normalize=True) #Variable objetiva binaria prueba

import pandas as pd
import numpy as np

# ---------------------------------------------------------------------
# Supongamos que df ya tiene la columna 'delayed' (1 = retraso >= 15 min)
# y la columna 'hour' (0-23) con la hora de salida o generada aleatoriamente
# ---------------------------------------------------------------------

# Calcular probabilidad de retraso según la hora
hour_delay = df.groupby("hour")["delayed"].mean()

# Este valor mide la variación de la probabilidad de retraso a lo largo del día
variation = hour_delay.max() - hour_delay.min()  # diferencia máxima-minima

# Comentarios explicativos:
# Este criterio mide cuánto cambia la probabilidad de retraso a lo largo del día;
# si la variación es alta, significa que la hora del vuelo influye de forma real
# en los retrasos, y el ratio entre datasets nos permite comparar cuál captura
# mejor ese patrón temporal sin necesidad de entrenar ni optimizar modelos.

print("Probabilidad de retraso por hora:")
print(hour_delay)
print("\nVariación de la probabilidad de retraso a lo largo del día:", variation)

